#Deployment do Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.3
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_PASSWORD
          value: "Kube#123"
        - name: POSTGRES_DB
          value: "kubenews"
---
# Definindo services para Postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
#Deployment do Kubenews
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: Desafio 05 - Diminuindo quantidade de replicas
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: rodrigoturatti/kube-news:latest
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "Kube#123"
        - name: DB_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
